### ISSUE TITLE
Optional fingerprint?

### ISSUE THREAD

**Issue by kamilchm** [aandrewww/winston-sentry-raven-transport#1]
Hi, I wonder if the `fingerprint` should be send if it's not set.
I get Sentry error when I use this lib as is:
```
Discarded invalid value for parameter 'fingerprint'

{
  "name": "fingerprint",
  "value": [
    null,
    "development"
  ]
}
```
Shouldn't we check if it's set before using it in https://github.com/aandrewww/winston-sentry-raven-transport/blob/23451feedff27a0ec0449102a8092da54e57cfdc/index.js#L77 ?

**Comment by aandrewww** [comment]
Yeah. You are totally right.
Can you install 1.0.2 version from NPM.
I added fingerprint as optional parameter.

https://github.com/aandrewww/winston-sentry-raven-transport/pull/2/commits/34663d0a56736fd95a8458ad9393a1b56af454ff

**Comment by kamilchm** [comment]
Works good, thx.

**Comment by aandrewww** [comment]
Welcome :)
