### ISSUE TITLE
fingerprint

### ISSUE THREAD

**Issue by VaclavObornik** [aandrewww/winston-sentry-raven-transport#10]
Hi @aandrewww !
I'd like to discuss the custom fingerprint possibility. I'm not sure, why there is only option to specify single key which (if present) is always combined with _environment_ value?

https://github.com/aandrewww/winston-sentry-raven-transport/blob/98e32bda94f617dcdf3b04f2b381fd02127db32f/index.js#L88-L90

I think it would be cool to not to do so and let the user specify all custom fingerprint values if needed. 

We, for example, need to have this fingerprint:
`['{{ default }}', info.message]` 
and we are not able to do it now.

It would be a breaking change, could I send a PR?

**Comment by aandrewww** [comment]
Yes, I totally agree with first parameter - `'{{ default }}'`, but why did you decide to group by `info.message`.

And of course, you can send PR. I will bump the major version

**Comment by VaclavObornik** [comment]
Maybe I wrote it in a wrong way. I thing the package should not modify this property at all. So the user is able to specify exact fingerprint he want from the outside. 

The '{{ default }}' and info.message is only example of need to specify custom fingerprint without the NODE_ENV variable, which is now impossible. 

I suggest to remove these three lines. User will be able to specify exact fingerprint by sending it to logger.log or by using Winston's format feature (if want to specify fingerprint for all log entries).

**Comment by aandrewww** [comment]
Cool. I'm waiting for your PR :)

**Comment by VaclavObornik** [comment]
https://github.com/aandrewww/winston-sentry-raven-transport/pull/11

**Comment by VaclavObornik** [comment]
@aandrewww Hi, is there any blocker I can help with? :) I'd really need to publish that if is it ok :)

**Comment by aandrewww** [comment]
sorry for the delay.
merged!

**Comment by VaclavObornik** [comment]
Thank you, could I ask you for publish? :)

**Comment by aandrewww** [comment]
of course :)
+ winston-sentry-raven-transport@1.2.0
