### ISSUE TITLE
Question: sentry.captureMessage error handling

### ISSUE THREAD

**Issue by JoelV** [aandrewww/winston-sentry-raven-transport#3]
Was wondering if I implemented some error handling on some sentry.captureMessage to retry or maybe implement some buffering to handle the flow of messages when calling sentry.captureMessage, would you be interested in merging that in?

**Comment by aandrewww** [comment]
Hello JoelV.
Could you tell a little more details ?
And... Yes, you can implement. We will see your solution :)

**Comment by JoelV** [comment]
I was thinking of implementing something like what the java driver does: https://docs.sentry.io/clients/java/config/#buffering-events-to-disk, except instead of using disk buffer the events to memory.

**Comment by aandrewww** [comment]
Hmmm.. Okay. You can implement it. Will be interesting to look at this :)
