### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'info' in undefined

### ISSUE THREAD

**Issue by AdamGerthel** [aandrewww/winston-sentry-raven-transport#5]
I've been getting this error lately:

> TypeError: Cannot use 'in' operator to search for 'info' in undefined
    at Sentry.log (<path>\node_modules\winston-sentry-raven-transport\index.js:72:17)

When logging via Winston in the following way:

```
// ..(Winston already configured for Sentry on server start)
const logger = require('winston')

functionThatHasCallback((err) => {
  if (err) {
    logger.error(err)
  }
}
```

Any idea what could cause it? Do I have to convert the error to a string before sending it to logger? The error doesn't occur if I use the built in console logger in Winston, only when using this package.

**Comment by aandrewww** [comment]
I know only one reason, why this could happen.
https://github.com/aandrewww/winston-sentry-raven-transport/blob/master/index.js#L72

If I execute this:
```'info' in undefined```
I’ll get the same error:
```TypeError: Cannot use 'in' operator to search for 'info' in undefined```

`levelsMap` is defined when creating instances of a class.
https://github.com/aandrewww/winston-sentry-raven-transport/blob/master/index.js#L10

I think you haven't created an instance of Sentry class.

```
const Sentry = require('winston-sentry-raven-transport');
new Sentry({...});
```

**Comment by aandrewww** [comment]
For example
```
const { createLogger, transports } = require('winston');
const Sentry = require('winston-sentry-raven-transport');

function getLogger() {
  return createLogger({
    ....
    ]
  });
```

**Comment by AdamGerthel** [comment]
Right, but obviously must've created an instance of Sentry, otherwise the error would never occur at all? I mean how would I even be using that line of code?

This is the file where I configure winston:
```
const winston = require('winston')
const Sentry = require('winston-sentry-raven-transport')

if (process.env.NODE_ENV === 'development') {
  winston.add(new winston.transports.Console)
}

if (process.env.SENTRY_DSN) {
  winston.add(new Sentry({
    dsn: process.env.SENTRY_DSN,
    config: {
      release: version,
      environment: process.env.NODE_ENV
    }
  }))
}

module.exports = winston
```

And that file is required first of all other files in my index file for the node server.

**Comment by AdamGerthel** [comment]
**Update**

Huh, this is really strange. I provided the config as an object like this: 
`winston.add(new Sentry(sentryConf))`

The variable sentryConf is an object that looks like this (I've replaced the real values with empty strings but the values are there and working in the real world scenario):

```
{ 
  dsn: '',
  config: { 
    release: '',
    environment: '' 
  } 
}
```
That didn't work. But this works:
`winston.add(new Sentry({ ...sentryConf }))`

How can that be?

**Comment by aandrewww** [comment]
It's because I mutate `opts` object via `options`:
https://github.com/aandrewww/winston-sentry-raven-transport/blob/master/index.js#L15
See
https://github.com/aandrewww/winston-sentry-raven-transport/commit/03f4f65886db3cf060a2ccb33d4de6dc7dd69775

Try to use 1.0.3 version
https://www.npmjs.com/package/winston-sentry-raven-transport/v/1.0.3

**Comment by AdamGerthel** [comment]
Ah, that makes perfect sense.. Will try the update once I work on that project again
