### ISSUE TITLE
sentry.javascript.node module

### ISSUE THREAD

**Issue by phil-rw** [aandrewww/winston-sentry-raven-transport#7]
Do you have any plans to migrate to the sentry.javascript.node module from Raven?

https://docs.sentry.io/platforms/node/

**Comment by aandrewww** [comment]
Yes, of course.
It's in progress.

**Comment by phil-rw** [comment]
Awesome! Is there any help we could provide?

**Comment by aandrewww** [comment]
Yes, but a little bit later :)
I'm gonna find free time and migrate to the sentry.javascript.node module.
After that, you can improve the library.

**Comment by AttilaSATAN** [comment]
Waiting here to implement when migration is done. :)

**Comment by aandrewww** [comment]
@phil-rw @AttilaSATAN  Guys, you can use https://github.com/aandrewww/winston-transport-sentry-node package
